import type { HackathonVoteTruthSummary } from "@/lib/hackathon-vote-truth"

export const ARCHIVED_HACKATHON_VOTE_TRUTH_ISO_DATE = "2026-03-25"
export const ARCHIVED_HACKATHON_VOTE_TRUTH_DATE_LABEL = "25 March 2026"

export const ARCHIVED_HACKATHON_VOTE_TRUTH: HackathonVoteTruthSummary = {
  source: "competition-public-snapshot",
  summaryUrl: "https://vote.rajeevg.com/api/reporting/public-summary",
  generatedAt: "2026-03-25T23:13:44.893Z",
  startedAt: "2026-03-25T15:18:40.027Z",
  finalizedAt: null,
  status: "ARCHIVED_EVENT_SNAPSHOT",
  totals: {
    totalVotes: 297,
    uniqueJudges: 37,
    totalEntries: 9,
    openEntries: 9,
    participatingJudges: 37,
    remainingVotes: 15,
    totalScore: 1916,
    averageScore: 6.45,
  },
  entries: [
    {
      rank: 1,
      slug: "what-s-my-frog",
      projectName: "What's My Frog",
      voteCount: 36,
      totalScore: 268,
      averageScore: 7.44,
      isVotingOpen: true,
    },
    {
      rank: 2,
      slug: "modellens",
      projectName: "ModelLens",
      voteCount: 33,
      totalScore: 235,
      averageScore: 7.12,
      isVotingOpen: true,
    },
    {
      rank: 3,
      slug: "planet-assisstant",
      projectName: "Planet Assisstant",
      voteCount: 32,
      totalScore: 214,
      averageScore: 6.69,
      isVotingOpen: true,
    },
    {
      rank: 4,
      slug: "planet-killer",
      projectName: "Planet Killer",
      voteCount: 33,
      totalScore: 213,
      averageScore: 6.45,
      isVotingOpen: true,
    },
    {
      rank: 5,
      slug: "trafficker-on-steriods",
      projectName: "Trafficker on Steriods",
      voteCount: 33,
      totalScore: 205,
      averageScore: 6.21,
      isVotingOpen: true,
    },
    {
      rank: 6,
      slug: "taxo-guard",
      projectName: "Taxo guard",
      voteCount: 32,
      totalScore: 197,
      averageScore: 6.16,
      isVotingOpen: true,
    },
    {
      rank: 7,
      slug: "brief-it",
      projectName: "Brief It",
      voteCount: 34,
      totalScore: 196,
      averageScore: 5.76,
      isVotingOpen: true,
    },
    {
      rank: 8,
      slug: "audience-insights-generator",
      projectName: "Audience Insights Generator",
      voteCount: 32,
      totalScore: 196,
      averageScore: 6.13,
      isVotingOpen: true,
    },
    {
      rank: 9,
      slug: "autopull-aliance",
      projectName: "Autopull Aliance",
      voteCount: 32,
      totalScore: 192,
      averageScore: 6,
      isVotingOpen: true,
    },
  ],
}
