import { portfolioProjects } from "@/lib/portfolio-projects"
import type { ContentInventoryRecord } from "@/lib/content-ops/types"
import { posts } from "#velite"

const POST_CLASSIFICATIONS = {
  "from-ai-pilots-to-business-value": {
    id: "E01",
    status: "Existing -> expand",
    workflowStatus: "live",
    kind: "post",
    pageClass: "Flagship",
    pillar: "Applied AI strategy",
    cluster: "Business value",
    format: "Flagship essay",
    audienceSegment: "Business leaders; transformation sponsors; operators",
    intent: "Informational + framework",
    discoveryMode: "Strategic discovery / AI search summaries",
    coreJtbd: "Help leaders move from experimentation theatre to one credible AI operating result.",
    differentiationAngle: "Grounds AI strategy in visible workflow wins rather than abstract transformation rhetoric.",
    evidence: "Live shipped products, delivery workflows, and operator framing already present across the site.",
    parentHubs: ["/ai", "/playbooks"],
    nextSteps: [
      "/ai",
      "/glossary/agentic-engineering",
      "/blog/how-we-built-the-hackathon-voting-app",
    ],
    indexation: "Index",
    priority: "P1",
    effort: "M",
    impact: "H",
    primaryKpi: "Authority traffic and high-intent lead-assist behavior",
    notes: "Keep standalone URL. Feature inside the AI hub as the business-value flagship.",
    relatedIds: ["A01", "A05", "I02", "D01"],
    sourceType: "existing_content",
    heroLabel: "Flagship",
  },
  "how-we-built-a-consented-first-party-analytics-stack": {
    id: "E02",
    status: "Existing -> hub anchor",
    workflowStatus: "live",
    kind: "post",
    pageClass: "Proof / case study",
    pillar: "Analytics engineering",
    cluster: "Measurement systems",
    format: "Case study",
    audienceSegment: "Analytics engineers; technical marketers",
    intent: "Informational + implementation",
    discoveryMode: "Problem-led discovery / technical search",
    coreJtbd: "Show what a consent-aware first-party analytics stack looks like in production.",
    differentiationAngle: "Proof-heavy walkthrough with real IDs, screenshots, architecture, and validation steps.",
    evidence: "Live property, GTM/sGTM, BigQuery, and site-owned analytics contract.",
    parentHubs: ["/analytics", "/proof"],
    nextSteps: [
      "/analytics",
      "/projects/site-analytics",
      "/blog/why-browser-consent-and-source-blending-make-marketing-measurement-harder",
    ],
    indexation: "Index",
    priority: "P1",
    effort: "M",
    impact: "H",
    primaryKpi: "Technical authority and project-route assists",
    notes: "Use as the proof node beneath the analytics flagship and surface its architecture in the hub.",
    relatedIds: ["A06", "A22", "E04", "E07", "P02"],
    sourceType: "existing_content",
    heroLabel: "Proof",
  },
  "how-we-built-the-hackathon-voting-app": {
    id: "E03",
    status: "Existing -> proof node",
    workflowStatus: "live",
    kind: "post",
    pageClass: "Proof / build log",
    pillar: "Agentic engineering",
    cluster: "Build workflows",
    format: "Build log",
    audienceSegment: "Builders; product-minded operators",
    intent: "Informational + implementation",
    discoveryMode: "Proof-led discovery / product-engineering search",
    coreJtbd: "Demonstrate how a real event-day product was scoped, shipped, validated, and instrumented.",
    differentiationAngle: "Shows sequencing, proof, and operational safeguards instead of abstract build advice.",
    evidence: "Live app, screenshots, analytics, and validation artifacts.",
    parentHubs: ["/ai", "/proof", "/projects"],
    nextSteps: [
      "/projects",
      "/projects/hackathon-voting-analytics",
      "/blog/why-browser-consent-and-source-blending-make-marketing-measurement-harder",
    ],
    indexation: "Index",
    priority: "P1",
    effort: "M",
    impact: "H",
    primaryKpi: "Proof-driven engagement and project-route traffic",
    notes: "Keep the URL, but position it as a canonical proof page in the proof hub and agentic-engineering cluster.",
    relatedIds: ["A03", "P03", "D02"],
    sourceType: "existing_content",
    heroLabel: "Build log",
  },
  "how-we-finished-the-ga4-property-setup-on-rajeevg-com": {
    id: "E04",
    status: "Existing -> supporting workflow",
    workflowStatus: "live",
    kind: "post",
    pageClass: "Workflow / playbook",
    pillar: "Analytics engineering",
    cluster: "Measurement systems",
    format: "Implementation guide",
    audienceSegment: "Analytics operators; technical marketers",
    intent: "Informational + workflow",
    discoveryMode: "Technical search / operational troubleshooting",
    coreJtbd: "Document the operational choices that turn a GA4 property into a useful reporting surface.",
    differentiationAngle: "Property-level proof with real configuration choices and screenshots.",
    evidence: "GA4 admin screenshots, realtime proof, and promoted custom definitions.",
    parentHubs: ["/analytics", "/playbooks"],
    nextSteps: [
      "/projects/site-analytics",
      "/blog/how-we-built-a-consented-first-party-analytics-stack",
      "/glossary/measurement-system-of-record",
    ],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "M",
    primaryKpi: "Long-tail implementation traffic",
    notes: "Treat as an operational child page under the broader measurement hub.",
    relatedIds: ["A06", "P04"],
    sourceType: "existing_content",
    heroLabel: "Playbook",
  },
  "git-workflow-for-beginners": {
    id: "E05",
    status: "Existing -> supporting bridge",
    workflowStatus: "live",
    kind: "post",
    pageClass: "Workflow / playbook",
    pillar: "Agentic engineering",
    cluster: "Delivery workflows",
    format: "Guide",
    audienceSegment: "Beginners; collaborators entering modern software workflows",
    intent: "Informational + workflow",
    discoveryMode: "Problem-led learning search",
    coreJtbd: "Help newcomers understand how safer delivery and review actually work.",
    differentiationAngle: "Beginner-friendly, visual explanation that bridges into the more advanced issue-driven delivery worldview.",
    evidence: "Visual walkthroughs and reusable workflow framing.",
    parentHubs: ["/playbooks", "/proof"],
    nextSteps: ["/ai", "/projects", "/blog/the-projects-behind-this-portfolio"],
    indexation: "Index",
    priority: "P2",
    effort: "S",
    impact: "M",
    primaryKpi: "Bridge traffic and assisted exploration into advanced workflows",
    notes: "Keep live, but de-emphasize relative to the flagship AI and analytics clusters.",
    relatedIds: ["D05"],
    sourceType: "existing_content",
    heroLabel: "Bridge guide",
  },
  "the-projects-behind-this-portfolio": {
    id: "E06",
    status: "Existing -> supporting proof",
    workflowStatus: "live",
    kind: "post",
    pageClass: "Proof / portfolio essay",
    pillar: "Business value and orchestration",
    cluster: "Proof assets",
    format: "Portfolio walkthrough",
    audienceSegment: "Potential collaborators; technical readers",
    intent: "Informational + proof",
    discoveryMode: "Branded discovery / portfolio exploration",
    coreJtbd: "Explain the system-thinking behind the public projects instead of just listing them.",
    differentiationAngle: "Turns the portfolio into a narrated map of product and system decisions.",
    evidence: "Public repos, live URLs, and detailed explanations of each project.",
    parentHubs: ["/projects", "/proof"],
    nextSteps: ["/projects", "/blog/how-we-built-the-hackathon-voting-app", "/ai"],
    indexation: "Index",
    priority: "P2",
    effort: "S",
    impact: "M",
    primaryKpi: "Project-route assists and credibility building",
    notes: "Keep as proof-supporting content and cross-link from project cards.",
    relatedIds: ["P01", "P03", "P04"],
    sourceType: "existing_content",
    heroLabel: "Proof",
  },
  "why-browser-consent-and-source-blending-make-marketing-measurement-harder": {
    id: "E07",
    status: "Existing -> flagship proof",
    workflowStatus: "live",
    kind: "post",
    pageClass: "Flagship",
    pillar: "Analytics engineering",
    cluster: "Measurement systems",
    format: "Flagship essay",
    audienceSegment: "Measurement engineers; technical marketers",
    intent: "Informational + framework",
    discoveryMode: "Problem-led discovery / AI search summaries",
    coreJtbd: "Explain why marketing measurement diverges across browser, consent, analytics, warehouse, and back-end truth layers.",
    differentiationAngle: "Quantified, case-backed explanation instead of generic privacy commentary.",
    evidence: "Hackathon vote counts, GA4 coverage gaps, and BigQuery absence all in one narrative.",
    parentHubs: ["/analytics", "/proof"],
    nextSteps: [
      "/analytics",
      "/projects/hackathon-voting-analytics",
      "/glossary/measurement-system-of-record",
    ],
    indexation: "Index",
    priority: "P1",
    effort: "M",
    impact: "H",
    primaryKpi: "Authority growth in measurement and privacy topics",
    notes: "Feature high in the analytics hub and link laterally to the stack case study and dashboards.",
    relatedIds: ["A06", "P03", "P04", "D03"],
    sourceType: "existing_content",
    heroLabel: "Flagship",
  },
} as const

const DASHBOARD_ASSETS: ContentInventoryRecord[] = [
  {
    id: "P01",
    title: "Projects index",
    status: "Existing -> hub",
    workflowStatus: "live",
    kind: "project",
    pageClass: "Interactive asset",
    pillar: "Business value and orchestration",
    cluster: "Proof assets",
    url: "/projects",
    format: "Hub page",
    audienceSegment: "Potential collaborators; technical readers",
    intent: "Informational + proof",
    discoveryMode: "Portfolio exploration",
    coreJtbd: "Give readers a working index of public shipped systems with real repos and real URLs.",
    differentiationAngle: "Acts as a proof library rather than a generic project gallery.",
    evidence: "Public repos and live URLs verified in checked-in metadata.",
    parentHubs: ["/proof"],
    nextSteps: ["/blog/the-projects-behind-this-portfolio", "/projects/site-analytics"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "H",
    primaryKpi: "Project page depth and assisted proof sessions",
    notes: "Promote as a hub inside the proof system, not just a nav destination.",
    tags: ["projects", "proof", "portfolio"],
    relatedIds: ["E06", "P02", "P03", "P04"],
    sourceType: "existing_content",
  },
  {
    id: "P02",
    title: "Main site analytics dashboard",
    status: "Existing -> interactive proof",
    workflowStatus: "live",
    kind: "dashboard",
    pageClass: "Interactive asset",
    pillar: "Analytics engineering",
    cluster: "Measurement systems",
    url: "/projects/site-analytics",
    format: "Dashboard",
    audienceSegment: "Analytics operators; technical marketers",
    intent: "Implementation + exploration",
    discoveryMode: "Tool-led discovery",
    coreJtbd: "Inspect the live GA4 performance and instrumentation quality of rajeevg.com.",
    differentiationAngle: "Turns the site’s own analytics stack into a working proof surface.",
    evidence: "Live GA4 data, project route, and existing reporting libraries.",
    parentHubs: ["/analytics", "/proof"],
    nextSteps: ["/blog/how-we-built-a-consented-first-party-analytics-stack", "/dashboard"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "H",
    primaryKpi: "Interactive proof sessions",
    notes: "Keep accessible from both the analytics hub and the content OS.",
    tags: ["analytics", "ga4", "dashboard"],
    relatedIds: ["E02", "E04", "A06"],
    sourceType: "existing_content",
  },
  {
    id: "P03",
    title: "Hackathon BigQuery analytics dashboard",
    status: "Existing -> interactive proof",
    workflowStatus: "live",
    kind: "dashboard",
    pageClass: "Interactive asset",
    pillar: "Analytics engineering",
    cluster: "Measurement systems",
    url: "/projects/hackathon-voting-analytics",
    format: "Dashboard",
    audienceSegment: "Analytics operators; product engineers",
    intent: "Implementation + exploration",
    discoveryMode: "Proof-led discovery",
    coreJtbd: "Explore the hackathon reporting surface that grounds the measurement discrepancy case study.",
    differentiationAngle: "Directly connects the public proof story to a working data product surface.",
    evidence: "Live and dummy modes plus verified dashboard artifacts.",
    parentHubs: ["/analytics", "/proof"],
    nextSteps: ["/blog/how-we-built-the-hackathon-voting-app", "/blog/why-browser-consent-and-source-blending-make-marketing-measurement-harder"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "H",
    primaryKpi: "Interactive proof depth",
    notes: "Feature as the proof asset under measurement reliability.",
    tags: ["analytics", "bigquery", "proof"],
    relatedIds: ["E03", "E07"],
    sourceType: "existing_content",
  },
  {
    id: "P04",
    title: "Hackathon GA4 reporting surface",
    status: "Existing -> interactive proof",
    workflowStatus: "live",
    kind: "dashboard",
    pageClass: "Interactive asset",
    pillar: "Analytics engineering",
    cluster: "Measurement systems",
    url: "/projects/hackathon-voting-analytics/google-analytics",
    format: "Dashboard",
    audienceSegment: "Analytics operators",
    intent: "Implementation + troubleshooting",
    discoveryMode: "Operational proof",
    coreJtbd: "Validate what the GA4 layer saw versus the source-of-truth product ledger.",
    differentiationAngle: "Completes the measurement discrepancy story with property-side evidence.",
    evidence: "Existing GA Data API route and audit artifacts.",
    parentHubs: ["/analytics", "/proof"],
    nextSteps: ["/projects/hackathon-voting-analytics", "/blog/how-we-finished-the-ga4-property-setup-on-rajeevg-com"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "M",
    primaryKpi: "Proof completeness",
    notes: "Keep visible as a sibling asset, not buried in the projects page.",
    tags: ["analytics", "ga4", "proof"],
    relatedIds: ["E04", "E07"],
    sourceType: "existing_content",
  },
]

const GLOSSARY_PAGES: ContentInventoryRecord[] = [
  {
    id: "G01",
    title: "Agentic engineering",
    status: "New -> concept node",
    workflowStatus: "approved",
    kind: "glossary",
    pageClass: "Concept / glossary node",
    pillar: "Agentic engineering",
    cluster: "Definitions",
    url: "/glossary/agentic-engineering",
    format: "Glossary page",
    audienceSegment: "Builders; technical operators",
    intent: "Definition + next-step routing",
    discoveryMode: "Entity-led discovery",
    coreJtbd: "Define the term in a way that actually helps people pick a working approach.",
    differentiationAngle: "Links the definition to workflow modes, risk, and proof pages instead of jargon alone.",
    evidence: "Derived from the site’s existing build-log and workflow content.",
    parentHubs: ["/ai"],
    nextSteps: ["/ai", "/blog/how-we-built-the-hackathon-voting-app"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "M",
    primaryKpi: "Glossary discovery and internal navigation assists",
    notes: "Bounded programmatic surface seeded from existing site vocabulary.",
    tags: ["glossary", "agents", "workflows"],
    relatedIds: ["A03", "E03", "E05"],
    sourceType: "glossary_page",
  },
  {
    id: "G02",
    title: "Measurement system of record",
    status: "New -> concept node",
    workflowStatus: "approved",
    kind: "glossary",
    pageClass: "Concept / glossary node",
    pillar: "Analytics engineering",
    cluster: "Definitions",
    url: "/glossary/measurement-system-of-record",
    format: "Glossary page",
    audienceSegment: "Analytics engineers; technical marketers",
    intent: "Definition + next-step routing",
    discoveryMode: "Entity-led discovery",
    coreJtbd: "Explain why the system of record differs from browser-observed analytics and how to reason about that gap.",
    differentiationAngle: "Grounds the definition in a real discrepancy case rather than abstract analytics vocabulary.",
    evidence: "Derived from the consent and hackathon measurement posts.",
    parentHubs: ["/analytics"],
    nextSteps: ["/analytics", "/blog/why-browser-consent-and-source-blending-make-marketing-measurement-harder"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "M",
    primaryKpi: "Internal navigation depth and glossary coverage",
    notes: "Acts as the clean conceptual bridge between the proof posts and playbooks.",
    tags: ["glossary", "analytics", "measurement"],
    relatedIds: ["E02", "E07", "P03", "P04"],
    sourceType: "glossary_page",
  },
  {
    id: "G03",
    title: "First-party analytics delivery",
    status: "New -> concept node",
    workflowStatus: "approved",
    kind: "glossary",
    pageClass: "Concept / glossary node",
    pillar: "Analytics engineering",
    cluster: "Definitions",
    url: "/glossary/first-party-analytics-delivery",
    format: "Glossary page",
    audienceSegment: "Analytics engineers; privacy-conscious marketers",
    intent: "Definition + implementation routing",
    discoveryMode: "Entity-led discovery",
    coreJtbd: "Clarify what first-party analytics delivery is and why it matters in modern measurement stacks.",
    differentiationAngle: "Uses the site’s real implementation and diagrams as the explanatory backbone.",
    evidence: "Derived from the consented first-party analytics stack content.",
    parentHubs: ["/analytics"],
    nextSteps: ["/blog/how-we-built-a-consented-first-party-analytics-stack", "/projects/site-analytics"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "M",
    primaryKpi: "Supporting-node visibility in analytics cluster",
    notes: "One of the bounded pSEO-safe concept pages seeded from firsthand work.",
    tags: ["glossary", "analytics", "gtm"],
    relatedIds: ["E02", "A06", "P02"],
    sourceType: "glossary_page",
  },
]

const DERIVED_IDEAS: ContentInventoryRecord[] = [
  {
    id: "D01",
    title: "The AI workflow review: how to find the first use case worth automating",
    status: "Derived -> queued",
    workflowStatus: "queued",
    kind: "idea",
    pageClass: "Workflow / playbook",
    pillar: "Applied AI strategy",
    cluster: "Business value",
    url: "/playbooks/ai-workflow-review",
    format: "Playbook",
    audienceSegment: "Business leaders; consultants",
    intent: "Informational + workflow",
    discoveryMode: "Need-state discovery",
    coreJtbd: "Turn the flagship AI strategy post into a practical scoping playbook.",
    differentiationAngle: "Derived directly from the business-value flagship so it inherits real operator framing.",
    evidence: "Source material comes from the existing AI pilots flagship and project proof pages.",
    parentHubs: ["/playbooks", "/ai"],
    nextSteps: ["/blog/from-ai-pilots-to-business-value"],
    indexation: "Noindex until approved",
    priority: "P1",
    effort: "M",
    impact: "H",
    primaryKpi: "Queued content quality",
    notes: "Seed this as a queue-ready draft starter in the editor.",
    tags: ["ai", "playbook", "workflow"],
    relatedIds: ["E01"],
    sourceType: "derived_opportunity",
    derivedFrom: ["E01"],
  },
  {
    id: "D02",
    title: "Single-screen product design for live event workflows",
    status: "Derived -> queued",
    workflowStatus: "queued",
    kind: "idea",
    pageClass: "Workflow / playbook",
    pillar: "Agentic engineering",
    cluster: "Build workflows",
    url: "/playbooks/single-screen-event-workflows",
    format: "Playbook",
    audienceSegment: "Builders; event operators",
    intent: "Informational + workflow",
    discoveryMode: "Problem-led search",
    coreJtbd: "Extract the single-screen UX and validation lessons from the hackathon voting app.",
    differentiationAngle: "Derived from a live product proof page instead of abstract UX theory.",
    evidence: "Hackathon product build log and project dashboards.",
    parentHubs: ["/playbooks", "/proof"],
    nextSteps: ["/blog/how-we-built-the-hackathon-voting-app"],
    indexation: "Noindex until approved",
    priority: "P1",
    effort: "M",
    impact: "M",
    primaryKpi: "Queued proof-backed content",
    notes: "Queue as a derivative workflow node.",
    tags: ["product", "workflow", "proof"],
    relatedIds: ["E03", "P03"],
    sourceType: "derived_opportunity",
    derivedFrom: ["E03"],
  },
  {
    id: "D03",
    title: "A measurement discrepancy checklist for GA4, BigQuery, and back-end truth",
    status: "Derived -> queued",
    workflowStatus: "queued",
    kind: "idea",
    pageClass: "Workflow / playbook",
    pillar: "Analytics engineering",
    cluster: "Measurement systems",
    url: "/playbooks/measurement-discrepancy-checklist",
    format: "Checklist",
    audienceSegment: "Analytics engineers; technical marketers",
    intent: "Informational + troubleshooting",
    discoveryMode: "Problem-led discovery",
    coreJtbd: "Turn the quantified discrepancy essay into an actionable diagnostic workflow.",
    differentiationAngle: "Checklist inherits hard-quant evidence from the existing flagship proof post.",
    evidence: "Hackathon measurements, GA4 counts, and warehouse gaps already documented.",
    parentHubs: ["/analytics", "/playbooks"],
    nextSteps: ["/blog/why-browser-consent-and-source-blending-make-marketing-measurement-harder"],
    indexation: "Noindex until approved",
    priority: "P1",
    effort: "S",
    impact: "H",
    primaryKpi: "Queued troubleshooting demand capture",
    notes: "Should later become a bounded role x workflow playbook candidate.",
    tags: ["analytics", "checklist", "measurement"],
    relatedIds: ["E07", "P03", "P04"],
    sourceType: "derived_opportunity",
    derivedFrom: ["E07"],
  },
  {
    id: "D04",
    title: "A safe GA4 property setup checklist for content-heavy sites",
    status: "Derived -> queued",
    workflowStatus: "queued",
    kind: "idea",
    pageClass: "Workflow / playbook",
    pillar: "Analytics engineering",
    cluster: "Measurement systems",
    url: "/playbooks/ga4-property-setup-checklist",
    format: "Checklist",
    audienceSegment: "Analytics operators",
    intent: "Informational + workflow",
    discoveryMode: "Long-tail implementation search",
    coreJtbd: "Condense the GA4 property setup write-up into a reusable checklist asset.",
    differentiationAngle: "Draws from a real property build rather than generic GA4 setup advice.",
    evidence: "Existing property setup post and site analytics dashboard.",
    parentHubs: ["/analytics", "/playbooks"],
    nextSteps: ["/blog/how-we-finished-the-ga4-property-setup-on-rajeevg-com"],
    indexation: "Noindex until approved",
    priority: "P2",
    effort: "S",
    impact: "M",
    primaryKpi: "Queued workflow coverage",
    notes: "Good supporting content for the measurement cluster.",
    tags: ["ga4", "analytics", "checklist"],
    relatedIds: ["E04", "P02"],
    sourceType: "derived_opportunity",
    derivedFrom: ["E04"],
  },
  {
    id: "D05",
    title: "Git workflows for AI-assisted teams",
    status: "Derived -> queued",
    workflowStatus: "queued",
    kind: "idea",
    pageClass: "Supporting / bridge content",
    pillar: "Agentic engineering",
    cluster: "Delivery workflows",
    url: "/playbooks/git-workflows-for-ai-teams",
    format: "Guide",
    audienceSegment: "Teams adopting agents or AI review",
    intent: "Informational + workflow",
    discoveryMode: "Bridge search",
    coreJtbd: "Extend the beginner Git guide into the more advanced AI-assisted delivery context.",
    differentiationAngle: "Bridges novice Git understanding with the repo practices already visible in the site’s project work.",
    evidence: "Existing beginner guide and the site’s issue-driven workflow patterns.",
    parentHubs: ["/playbooks", "/ai"],
    nextSteps: ["/blog/git-workflow-for-beginners"],
    indexation: "Noindex until approved",
    priority: "P2",
    effort: "S",
    impact: "M",
    primaryKpi: "Bridge content assists",
    notes: "Queue for later so the beginner post can route readers forward.",
    tags: ["git", "ai", "workflow"],
    relatedIds: ["E05"],
    sourceType: "derived_opportunity",
    derivedFrom: ["E05"],
  },
]

const HUB_PAGES: ContentInventoryRecord[] = [
  {
    id: "H01",
    title: "AI workflows and agentic engineering",
    status: "New -> hub",
    workflowStatus: "approved",
    kind: "hub",
    pageClass: "Hub",
    pillar: "Agentic engineering",
    cluster: "Hub",
    url: "/ai",
    format: "Hub page",
    audienceSegment: "Builders; operators; leaders",
    intent: "Informational + navigation",
    discoveryMode: "Top-level discovery",
    coreJtbd: "Help readers find the right flagship, workflow, proof, and glossary nodes for AI-enabled delivery work.",
    differentiationAngle: "Built from the site’s actual content graph instead of a marketing landing page.",
    evidence: "Existing AI and build-log content plus queued derivative playbooks.",
    parentHubs: ["/"],
    nextSteps: ["/playbooks", "/proof"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "H",
    primaryKpi: "Hub entrances and assisted article depth",
    notes: "Public IA anchor.",
    tags: ["hub", "ai", "agents"],
    relatedIds: ["E01", "E03", "G01"],
    sourceType: "hub_page",
  },
  {
    id: "H02",
    title: "Measurement, privacy, and analytics systems",
    status: "New -> hub",
    workflowStatus: "approved",
    kind: "hub",
    pageClass: "Hub",
    pillar: "Analytics engineering",
    cluster: "Hub",
    url: "/analytics",
    format: "Hub page",
    audienceSegment: "Analytics engineers; technical marketers",
    intent: "Informational + navigation",
    discoveryMode: "Top-level discovery",
    coreJtbd: "Turn the current analytics proof content into a navigable measurement system.",
    differentiationAngle: "Maps strategy, proof, dashboards, and glossary nodes into one measurement graph.",
    evidence: "Existing analytics posts and dashboards.",
    parentHubs: ["/"],
    nextSteps: ["/proof", "/projects/site-analytics"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "H",
    primaryKpi: "Analytics hub entrances and multi-page proof sessions",
    notes: "Public IA anchor.",
    tags: ["hub", "analytics", "measurement"],
    relatedIds: ["E02", "E04", "E07", "G02", "G03"],
    sourceType: "hub_page",
  },
  {
    id: "H03",
    title: "Playbooks and operator workflows",
    status: "New -> hub",
    workflowStatus: "approved",
    kind: "hub",
    pageClass: "Hub",
    pillar: "Workflow playbooks",
    cluster: "Hub",
    url: "/playbooks",
    format: "Hub page",
    audienceSegment: "Operators; builders; technical marketers",
    intent: "Informational + navigation",
    discoveryMode: "Top-level discovery",
    coreJtbd: "Gather tactical guides, queued playbooks, and workflow-first navigation in one place.",
    differentiationAngle: "Treats playbooks as the action layer beneath the flagships and proof pages.",
    evidence: "Existing beginner and analytics workflow content plus derived queue items.",
    parentHubs: ["/"],
    nextSteps: ["/ai", "/analytics"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "M",
    primaryKpi: "Workflow hub entrances",
    notes: "Public IA anchor.",
    tags: ["hub", "playbooks", "workflow"],
    relatedIds: ["E04", "E05", "D01", "D03"],
    sourceType: "hub_page",
  },
  {
    id: "H04",
    title: "Proof, case studies, and shipped systems",
    status: "New -> hub",
    workflowStatus: "approved",
    kind: "hub",
    pageClass: "Hub",
    pillar: "Proof assets",
    cluster: "Hub",
    url: "/proof",
    format: "Hub page",
    audienceSegment: "Decision makers; builders; collaborators",
    intent: "Informational + proof",
    discoveryMode: "Top-level discovery",
    coreJtbd: "Collect proof nodes, dashboards, and projects that demonstrate the site’s point of view in practice.",
    differentiationAngle: "Transforms scattered case studies and dashboards into a trust-transfer system.",
    evidence: "Existing posts, public projects, and reporting routes.",
    parentHubs: ["/"],
    nextSteps: ["/projects", "/analytics", "/ai"],
    indexation: "Index",
    priority: "P1",
    effort: "S",
    impact: "H",
    primaryKpi: "Proof sessions and project assists",
    notes: "Public IA anchor.",
    tags: ["hub", "proof", "projects"],
    relatedIds: ["E02", "E03", "E06", "P01", "P02", "P03", "P04"],
    sourceType: "hub_page",
  },
]

export function getExistingContentInventory(): ContentInventoryRecord[] {
  const postRecords = posts
    .filter((post) => post.slug in POST_CLASSIFICATIONS && !post.draft)
    .map((post) => {
      const config = POST_CLASSIFICATIONS[post.slug as keyof typeof POST_CLASSIFICATIONS]
      return {
        ...config,
        parentHubs: [...config.parentHubs],
        nextSteps: [...config.nextSteps],
        relatedIds: [...config.relatedIds],
        title: post.title,
        url: `/blog/${post.slug}`,
        tags: post.tags,
        sourcePath: `content/posts/${post.slug}.mdx`,
        sourceSlug: post.slug,
      } satisfies ContentInventoryRecord
    })

  const projectRecords = DASHBOARD_ASSETS
    .map((asset) => {
      if (asset.kind === "project") return asset
      return asset
    })

  const externalProjectCards = portfolioProjects
    .filter((project) => project.slug !== "rajeevg-com" && project.slug !== "hackathon-voting-app")
    .map(
      (project, index) =>
        ({
          id: `PX${index + 1}`,
          title: project.title,
          status: "Existing -> supporting proof",
          workflowStatus: "live",
          kind: "project",
          pageClass: "Proof / external project",
          pillar: "Business value and orchestration",
          cluster: "Proof assets",
          url: project.liveUrl,
          format: "External project",
          audienceSegment: "Collaborators; technical readers",
          intent: "Proof + exploration",
          discoveryMode: "Portfolio exploration",
          coreJtbd: "Show related shipped systems that reinforce the site’s operator credibility.",
          differentiationAngle: project.tagline,
          evidence: project.summary,
          parentHubs: ["/projects", "/proof"],
          nextSteps: ["/blog/the-projects-behind-this-portfolio"],
          indexation: "External",
          priority: "P2",
          effort: "S",
          impact: "M",
          primaryKpi: "Project proof depth",
          notes: project.howItWorks,
          tags: project.tech,
          relatedIds: ["E06", "P01"],
          sourceType: "existing_content",
          sourceSlug: project.slug,
        }) satisfies ContentInventoryRecord
    )

  return [
    ...HUB_PAGES,
    ...postRecords,
    ...projectRecords,
    ...externalProjectCards,
    ...GLOSSARY_PAGES,
    ...DERIVED_IDEAS,
  ]
}
